import Navbar from './components/Navbar'
import { Raleway } from "next/font/google";
import './globals.css'

export const metadata = {
  title: 'Photo Gallery Compilation',
  description: 'Generated by create next app',
}

const raleway = Raleway({
  weight: "400",
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={raleway.className}>
      <body>
      <Navbar />
        {children}
        </body>
    </html>
  )
}
